// TABS/SETTINGS/CompanyDetailsTab/CompanyDetailsTab.jsx

import React from "react";
import { Building2 } from "lucide-react";

const INFO_ROWS = [
    { label: "Company Name", value: "OfferWale Baba" },
    { label: "Business Type", value: "Wholesale & Retail" },
    { label: "GSTIN", value: "07AABCU9603R1ZX" },
    { label: "PAN Number", value: "AABCU9603R" },
    { label: "CIN", value: "U74999DL2020PTC123456" },
    { label: "Phone", value: "+91 98765 43210" },
    { label: "Email", value: "info@offerwalebaba.com" },
    { label: "Website", value: "www.offerwalebaba.com" },
];

const ADDRESS_ROWS = [
    { label: "Address Line 1", value: "14, Azad Market Road" },
    { label: "Address Line 2", value: "Near Metro Station" },
    { label: "City", value: "Delhi" },
    { label: "State", value: "Delhi" },
    { label: "Pincode", value: "110006" },
    { label: "Country", value: "India" },
];

function ReadOnlyRow({ label, value }) {
    return (
        <div className="flex justify-between py-2 border-b border-gray-50">
            <span className="text-xs text-gray-400">{label}</span>
            <span className="text-sm text-gray-700 font-medium">{value}</span>
        </div>
    );
}

export default function CompanyDetailsTab() {
    return (
        <div className="space-y-5 bg-gray-50 min-h-screen px-1 py-1">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 pb-3 border-b border-gray-200">
                <div>
                    <h2 className="text-xl font-semibold text-gray-900">Company Details</h2>
                    <p className="text-sm text-gray-400 mt-0.5">Manage your business information and branding</p>
                </div>
                <button
                    type="button"
                    className="bg-gray-900 text-white text-sm font-medium px-4 py-2 rounded-lg hover:bg-gray-700 transition-colors inline-flex items-center gap-2"
                >
                    Edit Details
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <div className="bg-white rounded-xl border border-gray-200 p-5">
                    <h3 className="text-sm font-semibold text-gray-700 mb-4">Business Information</h3>
                    {INFO_ROWS.map((row) => (
                        <ReadOnlyRow key={row.label} label={row.label} value={row.value} />
                    ))}
                </div>

                <div className="bg-white rounded-xl border border-gray-200 p-5">
                    <h3 className="text-sm font-semibold text-gray-700 mb-3">Registered Address</h3>
                    {ADDRESS_ROWS.map((row) => (
                        <ReadOnlyRow key={row.label} label={row.label} value={row.value} />
                    ))}

                    <h3 className="text-sm font-semibold text-gray-700 mt-5 mb-3">Branding</h3>
                    <div className="w-20 h-20 bg-gray-100 border border-gray-200 rounded-xl flex items-center justify-center text-gray-300">
                        <Building2 size={28} />
                    </div>
                    <p className="text-xs text-gray-400 mt-2">Upload company logo (PNG, JPG — max 2MB)</p>
                    <div className="w-full h-16 bg-gray-50 border border-dashed border-gray-200 rounded-lg flex items-center justify-center text-xs text-gray-400 mt-3">
                        Letterhead preview
                    </div>
                </div>
            </div>

            <div className="bg-white rounded-xl border border-gray-200 p-5">
                <h3 className="text-sm font-semibold text-gray-700 mb-4">GST Configuration</h3>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div>
                        <p className="text-xs text-gray-400 mb-1">Default GST Rate</p>
                        <p className="text-sm text-gray-700 font-medium">18%</p>
                    </div>
                    <div>
                        <p className="text-xs text-gray-400 mb-1">GST Type</p>
                        <p className="text-sm text-gray-700 font-medium">Regular</p>
                    </div>
                    <div>
                        <p className="text-xs text-gray-400 mb-1">HSN/SAC Code</p>
                        <p className="text-sm text-gray-700 font-medium">6217</p>
                    </div>
                </div>
                <div className="bg-blue-50 border border-blue-100 rounded-lg px-4 py-2 mt-4">
                    <p className="text-xs text-blue-600">
                        GST details are used on all invoices and purchase bills generated by the system.
                    </p>
                </div>
            </div>
        </div>
    );
}
